### ISSUE TITLE
New and missing combined authorities

### ISSUE THREAD

**Issue by chris48s** [mysociety/uk_local_authority_names_and_codes#10]
**Missing:**
E47000013 - East Midlands. ID: `EMCA`

**New authorities:**
Greater Lincolnshire Combined Authority. Suggested ID: `GLCA`
Hull and East Yorkshire Mayoral Combined Authority Suggested ID: `HYCA`
No GSS codes for these two yet

**Comment by ajparsons** [comment]
Ok those are in!
