### ISSUE TITLE
Some county-la data is wrong

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/uk_local_authority_names_and_codes#5]
Councils with Errors:

Bolsover District Council
Chesterfield Borough Council
Braintree District Council
Chelmsford City Council
Colchester Borough Council
Maldon District Council
Tendring District Council
Uttlesford District Council
Basingstoke and Deane Borough Council
Eastleigh Borough Council
New Forest District Council
Rushmoor Borough Council
Test Valley Borough Council
North Hertfordshire District Council
St Albans City and District Council
Stevenage Borough Council
Ashford Borough Council
Canterbury City Council
Dover District Council
Folkestone and Hythe District Council
Swale Borough Council
Thanet District Council
Burnley Borough Council
Hyndburn Borough Council
Lancaster City Council
Pendle Borough Council
Ribble Valley Borough Council
Rossendale Borough Council
West Lindsey District Council
Scarborough Borough Council
Bassetlaw District Council
East Staffordshire Borough Council
Staffordshire Moorlands District Council
Epsom and Ewell Borough Council
Mole Valley District Council
Reigate and Banstead Borough Council
Tandridge District Council
Waverley Borough Council
Adur District Council

**Comment by ajparsons** [comment]
Should be resolved through https://github.com/mysociety/uk_local_authority_names_and_codes/pull/6
