### ISSUE TITLE
New devolution deals

### ISSUE THREAD

**Issue by ajparsons** [mysociety/uk_local_authority_names_and_codes#7]
In progress, but not there yet:

[https://www.gov.uk/government/publications/east-midlands-devolution-deal](https://www.google.com/url?q=https://www.gov.uk/government/publications/east-midlands-devolution-deal&sa=D&source=docs&ust=1667919230198214&usg=AOvVaw2R6A8xAHlvUjPzNEO4tMXn)

[https://www.gov.uk/government/publications/york-and-north-yorkshire-devolution-deal](https://www.google.com/url?q=https://www.gov.uk/government/publications/york-and-north-yorkshire-devolution-deal&sa=D&source=docs&ust=1667919230198361&usg=AOvVaw0UQqQFe6bo1thi_h73yMoJ)

**Comment by GeoWill** [comment]
Getting there... 
https://www.legislation.gov.uk/uksi/2023/1432/contents/made

There's also the combination of North East CA and North of Tyne CA ([announcement](https://www.northoftyne-ca.gov.uk/news/devo/)), and Norfolk. But the latter isn't imminent. 

Suggested IDs:

York and North Yorkshire: **YNYCA**
East Midlands: **EMCA**
North East: :thinking: ~NECA~  **NETCA** :shrug:

**Comment by ajparsons** [comment]
Arrgh, would like to keep them to 4 letters but see the problem :(

**Comment by GeoWill** [comment]
YNYC and NEMC maybe then?

**Comment by ajparsons** [comment]
Yeahhhh

**Comment by ajparsons** [comment]
York and North Yorkshire has been added as YNYC. I have taken a guess on the code that ONS will assign - but will check that happens...

**Comment by GeoWill** [comment]
We decided to jump the gun and so I'm going to create these three in EE today. Will just have to delete them if the legislation doesn't happen, but given parties are selecting candidates we need something to exist in our system. 
Just to confirm I'll go for 'YNYC', 'NEMC' and 'EMCA'. I'm leaving the GSS codes blank for now.
